// >>> FLAVOR_CONFIG_START (generated by flutter_archkit)
import com.android.build.gradle.AppExtension

val android = project.extensions.getByType(AppExtension::class.java)

android.apply {
    flavorDimensions("default")

    productFlavors {
        create("dev") {
            dimension = "default"
            applicationId = "com.brand.kharcha.dev"
            resValue(type = "string", name = "app_name", value = "Kharcha Loan Management Dev")
        }
        create("prod") {
            dimension = "default"
            applicationId = "com.brand.kharcha"
            resValue(type = "string", name = "app_name", value = "Kharcha Loan Management")
        }
    }

    buildFeatures.resValues = true
}
// <<< autogenerated FLAVOR_CONFIG_END
